# Generated by Django 6.0 on 2026-07-15 14:18

import uuid

from django.db import migrations, models


def populate_user_uuid(apps, schema_editor):
    User = apps.get_model("users", "User")

    for user in User.objects.filter(uuid__isnull=True).iterator():
        user.uuid = uuid.uuid4()
        user.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                null=True,
                editable=False,
                verbose_name="UUID",
            ),
        ),
        migrations.RunPython(
            populate_user_uuid,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                editable=False,
                verbose_name="UUID",
            ),
        ),
    ]