# Generated by Django 6.0 on 2026-05-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vk_bot', '0001_initial'),
        ('django_pgwatch', '0002_install_pg_functions'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward migration - create trigger
            sql="""
            CREATE TRIGGER notify_geo_tracking_trip_changes
                AFTER INSERT OR UPDATE OR DELETE ON geo_tracking_trip
                FOR EACH ROW 
                EXECUTE FUNCTION notify_data_change();
            """,
            # Reverse migration - drop trigger
            reverse_sql="""
            DROP TRIGGER IF EXISTS notify_geo_tracking_trip_changes ON geo_tracking_trip;
            """
        ),
    ]
