# Generated by Django 6.0 on 2026-01-06 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('year_of_manufacture', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Год выпуска')),
                ('mileage', models.IntegerField(help_text='Пробег (км)', verbose_name='Пробег')),
                ('number', models.CharField(max_length=6, verbose_name='Госномер')),
                ('vin', models.CharField(max_length=17, validators=[django.core.validators.MinLengthValidator(17)], verbose_name='VIN')),
            ],
        ),
    ]
