# Generated by Django 6.0 on 2026-01-06 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_created_at_vehicle_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='number',
            field=models.CharField(max_length=6, unique=True, verbose_name='Госномер'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17)], verbose_name='VIN'),
        ),
    ]
