# Generated by Django 6.0 on 2026-03-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_model_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='purchased_at',
            field=models.DateTimeField(null=True, verbose_name='Дата и время приобретения'),
        ),
    ]
