# Generated by Django 6.0 on 2026-01-07 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_vehicle_number_alter_vehicle_vin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Наименование')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Брэнд',
                'verbose_name_plural': 'Брэнды',
            },
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Транспортное средство', 'verbose_name_plural': 'Транспортные средства'},
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('PCR', 'Легковой'), ('BUS', 'Автобус'), ('LRR', 'Грузовой')], max_length=3, verbose_name='Тип')),
                ('number_of_seats', models.IntegerField(verbose_name='Количество посадочных мест')),
                ('tank_capacity_l', models.IntegerField(help_text='Объем бака (л)', verbose_name='Объем бака')),
                ('load_capacity_kg', models.IntegerField(help_text='Грузоподъемность (кг)', verbose_name='Грузоподъемность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vehicle.brand', verbose_name='Брэнд')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='vehicle.model', verbose_name='Модель'),
        ),
    ]
