# Generated by Django 6.0 on 2026-01-07 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_brand_alter_vehicle_options_model_vehicle_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vehicle.model', verbose_name='Модель'),
        ),
    ]
