# Generated by Django 6.0 on 2026-01-11 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('vehicle', '0006_remove_model_brand_delete_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='enterprise.enterprise'),
        ),
    ]
