# Generated by Django 6.0 on 2026-01-12 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_delete_driver'),
        ('vehicle', '0007_vehicle_enterprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=35, verbose_name='Фвмилия')),
                ('TIN', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enterprise.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicles',
            field=models.ManyToManyField(related_name='drivers', through='vehicle.VehicleDriver', through_fields=('driver', 'vehicle'), to='vehicle.vehicle'),
        ),
    ]
