# Generated by Django 6.0 on 2026-01-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_driver_vehicledriver_driver_vehicles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AddField(
            model_name='vehicledriver',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
