# Generated by Django 6.0 on 2026-01-13 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_alter_driver_options_vehicledriver_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicledriver',
            options={'verbose_name': 'Машина водителя', 'verbose_name_plural': 'Машины и водители'},
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(max_length=35, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='vehicledriver',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='vehicledriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='vehicledriver',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle', verbose_name='Машина'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicledriver',
            unique_together={('driver', 'vehicle')},
        ),
    ]
