# Generated by Django 6.0 on 2026-01-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_alter_enterprise_name'),
        ('vehicle', '0010_alter_vehicledriver_options_alter_driver_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledriver',
            name='enterprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enterprise.enterprise'),
            preserve_default=False,
        ),
    ]
