# Generated by Django 6.0 on 2026-01-16 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_alter_enterprise_options'),
        ('vehicle', '0011_vehicledriver_enterprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='vehicles',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drivers',
            field=models.ManyToManyField(related_name='vehicles', through='vehicle.VehicleDriver', through_fields=('vehicle', 'driver'), to='vehicle.driver'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='drivers', to='enterprise.enterprise', verbose_name='Предприятие'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vehicles', to='enterprise.enterprise', verbose_name='Предприятие'),
        ),
        migrations.AlterField(
            model_name='vehicledriver',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_driver_pairs', to='enterprise.enterprise', verbose_name='Предприятие'),
        ),
    ]
