# Generated by Django 6.0 on 2026-01-16 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_alter_enterprise_options'),
        ('vehicle', '0012_remove_driver_vehicles_vehicle_drivers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='enterprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='vehicles', to='enterprise.enterprise', verbose_name='Предприятие'),
            preserve_default=False,
        ),
    ]
