# Generated by Django 6.0 on 2026-01-31 19:03

import django.db.models.deletion
import taxi_manager.vehicle.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0007_alter_manager_unique_together'),
        ('vehicle', '0013_alter_vehicle_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=17, unique=True, validators=[taxi_manager.vehicle.validators.vin_validator], verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='vehicledriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vehicle.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='vehicledriver',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vehicle_driver_pairs', to='enterprise.enterprise', verbose_name='Предприятие'),
        ),
        migrations.AlterField(
            model_name='vehicledriver',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vehicle.vehicle', verbose_name='Машина'),
        ),
    ]
