services:
  taxi-manager:
    # build: .
    image: metacortex687/taxi-manager
    restart: always
    ports:
      - 80:8000
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}  
      - DJANGO_SUPERUSER_NAME=${DJANGO_SUPERUSER_NAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - PYTHONUNBUFFERED=1
    command: sh -c "make migrate && make ensure-superuser  && make ensure-demo-data && make run-gunicorn"
    depends_on:
      db:
        condition: service_healthy   
  db:
    image: postgis/postgis:16-3.5
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  pgdata: