events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream taxi-manager {
        server taxi-manager:8000;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://taxi-manager; 
        }

        location /static/ {
            alias  /static/;
        }
    }

}


