events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream taxi-manager {
        server unix:/run/uwsgi/taxi-manager.sock; # взаимодействие с uwsgi через Unix-сокет
        # server taxi-manager:8000;
    }

    server {
        listen 80;
        server_name localhost;
       
        client_max_body_size 75M;

        location = /report.html {
            alias /data/goaccess/report.html;
        }

        location / {
            uwsgi_pass  taxi-manager;
            include     /etc/nginx/uwsgi_params;
        }

        location /static/ {
            alias  /static/;
        }


    }

}


