# Generated by Django 6.0 on 2026-03-16 09:25

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CreateExtension("postgis")
    ]
