# Generated by Django 6.0 on 2026-03-21 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_tracking', '0003_alter_vehiclelocation_location'),
        ('vehicle', '0004_vehicle_purchased_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rides', to='vehicle.vehicle', verbose_name='Автомобиль')),
            ],
        ),
    ]
