# Generated by Django 6.0 on 2026-03-21 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_enterprise_time_zone'),
        ('geo_tracking', '0004_trip'),
        ('vehicle', '0004_vehicle_purchased_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trips', to='enterprise.enterprise', verbose_name='Предприятие'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trips', to='vehicle.vehicle', verbose_name='Автомобиль'),
        ),
    ]
