# Generated by Django 6.0 on 2026-03-22 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_enterprise_time_zone'),
        ('geo_tracking', '0005_trip_enterprise_alter_trip_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocation',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='locations', to='enterprise.enterprise', verbose_name='Предприятие'),
        ),
    ]
