# Generated by Django 6.0 on 2026-04-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_carmileagereport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmileagereportvalue',
            name='count_trip',
            field=models.IntegerField(default=0, verbose_name='Поездок'),
            preserve_default=False,
        ),
    ]
