# Generated by Django 6.0 on 2026-04-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_carmileagereport_options_carroutesreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает формирования'), ('PROCESSING', 'Формируется'), ('DONE', 'Готов'), ('ERROR', 'Ошибка')], default='DONE', max_length=10),
            preserve_default=False,
        ),
    ]
