# Generated by Django 6.0 on 2026-07-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkAccount',
            fields=[
                ('user_uuid', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='UUID пользователя taxi_manager')),
                ('chat_user_id', models.BigIntegerField(unique=True, verbose_name='Идентификатор пользователя чата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата привязки')),
            ],
            options={
                'verbose_name': 'Привязка учётной записи',
                'verbose_name_plural': 'Привязки учётных записей',
            },
        ),
    ]
