"""
Django settings for taxi_manager project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from dotenv import load_dotenv

import dj_database_url

from pathlib import Path

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", False)

ALLOWED_HOSTS = ["*"]
INTERNAL_IPS = [
    "127.0.0.1",
    "0.0.0.0",
    "localhost"
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "djoser",
    "rest_framework.authtoken",
    "django_bootstrap5",
    "django_filters",
    "django.contrib.gis",
    "django.contrib.postgres",
    "rest_framework_gis",
    "import_export",
    'django_pgwatch',
    "django_prometheus",
    "django_tasks_db",
    # "silk",
    # 'dj_rest_auth',
    "taxi_manager.infrastructure.users",
    "taxi_manager.infrastructure.vehicle",
    "taxi_manager.infrastructure.enterprise",
    "taxi_manager.infrastructure.api_v1",
    "taxi_manager.infrastructure.simply_site",
    "taxi_manager.infrastructure.vanilla_frontend",
    "taxi_manager.infrastructure.time_zones",
    "taxi_manager.infrastructure.geo_tracking",
    "taxi_manager.infrastructure.demo_data",
    "taxi_manager.infrastructure.geocoding",
    "taxi_manager.infrastructure.exchange",
    "taxi_manager.infrastructure.reports",
    "taxi_manager.infrastructure.react_frontend",
    "taxi_manager.infrastructure.vk_bot",
    "taxi_manager.infrastructure.cache_manager",
    "taxi_manager.infrastructure.observability",
]

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "taxi_manager.infrastructure.observability.middleware.RequestTraceLoggingMiddleware",
    # "silk.middleware.SilkyMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = "taxi_manager.infrastructure.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "taxi_manager.infrastructure.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        conn_max_age=600,
        engine="django_prometheus.db.backends.postgis",
        test_options={"NAME": "mytestdatabase"},
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR.parent / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        #'rest_framework.authentication.BasicAuthentication',
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "EXCEPTION_HANDLER": "taxi_manager.infrastructure.api_v1.utils.custom_exception_handler",
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
    ],
}

ADDRESS_PROVIDER = {
    "URL": "https://us1.locationiq.com/v1/reverse",
    "DELAY_REQUEST": 0.1,
    "KEY": os.getenv("LOCATIONIQ_KEY"),
    "FALLBACK_RADIUS_M": 50,
}


from import_export.formats import base_formats

IMPORT_EXPORT_FORMATS = [base_formats.JSON, base_formats.CSV]

TASKS = {
    "default": {
        # "BACKEND": "django.tasks.backends.immediate.ImmediateBackend",
        "BACKEND": "django_tasks_db.DatabaseBackend",
        "QUEUES": ["default", "reports", "geocoding"],
    }
}


USE_VITE_DEV_SERVER = os.getenv("USE_VITE_DEV_SERVER", default=False)

VK_BOT_TOKEN=os.getenv("VK_BOT_TOKEN")
VK_BOT_GROUP_ID=os.getenv("VK_BOT_GROUP_ID")


TESTING = "test" in sys.argv or "PYTEST_VERSION" in os.environ



#Настрйоки кэша
CACHE_ENABLED=True


DJANGO_MEMCACHED_LOCATION=os.getenv("DJANGO_MEMCACHED_LOCATION")
if DJANGO_MEMCACHED_LOCATION and CACHE_ENABLED:
    CACHES = {
        "default": {
            "BACKEND": "django_prometheus.cache.backends.memcached.PyMemcacheCache",
            "LOCATION": DJANGO_MEMCACHED_LOCATION,
            # "LOCATION": "memcached:11211",
            #"LOCATION": "unix:/run/memcached/memcached.sock",

        }
    }

if not CACHE_ENABLED:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
    }
}


#Опциональное включение профайлера silk
PROFILER_SILK_ENBLE = False

if PROFILER_SILK_ENBLE:
    INSTALLED_APPS = [*INSTALLED_APPS, "silk"]

    MIDDLEWARE = ["silk.middleware.SilkyMiddleware", *MIDDLEWARE]


#Опциональное включение профайлера DEBUG_TOOLBAR_ENABLE
DEBUG_TOOLBAR_ENABLE = False

DEBUG_TOOLBAR_ENABLE = DEBUG_TOOLBAR_ENABLE and DEBUG and not TESTING 

if DEBUG_TOOLBAR_ENABLE:
    INSTALLED_APPS = [
        *INSTALLED_APPS,
        "debug_toolbar",
    ]
    MIDDLEWARE = [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
        # "debug_toolbar.middleware.show_toolbar_with_docker",
        *MIDDLEWARE,
    ]


PROMETHEUS_EXPORT_MIGRATIONS = False #True для сбора метрик применения миграций


DJOSER = {
    "SERIALIZERS": {
        "current_user": (
            "taxi_manager.infrastructure.users.serializers."
            "CurrentUserSerializer"
        ),
    },
}


if test_output_dir := os.getenv("TEST_OUTPUT_DIR"):
    TEST_RUNNER = "xmlrunner.extra.djangotestrunner.XMLTestRunner"
    TEST_OUTPUT_DIR = test_output_dir