# Generated by Django 6.0 on 2026-03-25 03:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=500)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
            ],
        ),
    ]
