# Generated by Django 6.0 on 2026-03-16 10:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo_tracking', '0001_postgis'),
        ('vehicle', '0004_vehicle_purchased_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('tracked_at', models.DateTimeField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='locations', to='vehicle.vehicle', verbose_name='Автомобиль')),
            ],
        ),
    ]
