# Generated by Django 6.0 on 2026-03-16 11:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_tracking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelocation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
