# Generated by Django 6.0 on 2026-01-11 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Наименование')),
                ('city', models.CharField(max_length=25, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=35, verbose_name='Фвмилия')),
                ('TIN', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enterprise.enterprise')),
            ],
        ),
    ]
