# Generated by Django 6.0 on 2026-03-12 15:16

import django.db.models.deletion
import taxi_manager.time_zones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('time_zones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='time_zone',
            field=models.ForeignKey(default=taxi_manager.time_zones.models.TimeZone.UTC, on_delete=django.db.models.deletion.RESTRICT, to='time_zones.timezone'),
        ),
    ]
