# Generated by Django 6.0 on 2026-01-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_delete_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='name',
            field=models.CharField(max_length=35, unique=True, verbose_name='Наименование'),
        ),
    ]
