# Generated by Django 6.0 on 2026-01-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_alter_enterprise_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprise',
            options={'verbose_name': 'Предприятие', 'verbose_name_plural': 'Предприятия'},
        ),
    ]
