# Generated by Django 6.0 on 2026-01-18 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_alter_enterprise_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enterprise.enterprise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.AddField(
            model_name='enterprise',
            name='manager_users',
            field=models.ManyToManyField(related_name='managed_enterprises', through='enterprise.Manager', through_fields=('enterprise', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
