# Generated by Django 6.0 on 2026-01-18 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_manager_enterprise_manager_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enterprise.enterprise', verbose_name='Предприятие'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
