# Generated by Django 6.0 on 2026-01-18 13:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0006_alter_manager_enterprise_alter_manager_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='manager',
            unique_together={('user', 'enterprise')},
        ),
    ]
