# Generated by Django 6.0 on 2026-02-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0007_alter_manager_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='eyar_of_foundation',
            field=models.DateField(null=True, verbose_name='год основания'),
        ),
    ]
