# Generated by Django 6.0 on 2026-02-03 13:14

import django.core.validators
import django.db.models.deletion
import taxi_manager.vehicle.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('PCR', 'Легковой'), ('BUS', 'Автобус'), ('LRR', 'Грузовой')], max_length=3, verbose_name='Тип')),
                ('number_of_seats', models.IntegerField(verbose_name='Количество посадочных мест')),
                ('tank_capacity_l', models.IntegerField(help_text='Объем бака (л)', verbose_name='Объем бака')),
                ('load_capacity_kg', models.IntegerField(help_text='Грузоподъемность (кг)', verbose_name='Грузоподъемность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=35, verbose_name='Фамилия')),
                ('TIN', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='drivers', to='enterprise.enterprise', verbose_name='Предприятие')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('year_of_manufacture', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Год выпуска')),
                ('mileage', models.IntegerField(help_text='Пробег (км)', verbose_name='Пробег')),
                ('number', models.CharField(max_length=6, unique=True, verbose_name='Госномер')),
                ('vin', models.CharField(max_length=17, unique=True, validators=[taxi_manager.vehicle.validators.vin_validator], verbose_name='VIN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vehicles', to='enterprise.enterprise', verbose_name='Предприятие')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vehicle.model', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
        migrations.CreateModel(
            name='VehicleDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vehicle.driver', verbose_name='Водитель')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vehicle_driver_pairs', to='enterprise.enterprise', verbose_name='Предприятие')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vehicle.vehicle', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'Машина водителя',
                'verbose_name_plural': 'Машины и водители',
                'unique_together': {('driver', 'vehicle')},
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drivers',
            field=models.ManyToManyField(related_name='vehicles', through='vehicle.VehicleDriver', through_fields=('vehicle', 'driver'), to='vehicle.driver'),
        ),
    ]
