# Generated by Django 6.0 on 2026-02-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='color',
            field=models.CharField(blank=True, default=True, max_length=30),
        ),
    ]
