# Generated by Django 6.0 on 2026-03-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_model_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='color',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
