# Generated by Django 6.0 on 2026-04-08 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_carmileagereportvalue_delete_floatreportvalue'),
        ('time_zones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='time_zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='time_zones.timezone'),
            preserve_default=False,
        ),
    ]
