# Generated by Django 6.0 on 2026-04-09 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_enterprise_time_zone'),
        ('reports', '0003_report_time_zone'),
        ('vehicle', '0004_vehicle_purchased_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmileagereport',
            options={'verbose_name': 'Пробег автомобиля за период'},
        ),
        migrations.AddField(
            model_name='defaultuservalues',
            name='frequency',
            field=models.CharField(choices=[('DAY', 'День'), ('WEEK', 'Неделя'), ('MONTH', 'Месяц'), ('YEAR', 'Год')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='carmileagereportvalue',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='carmileagereportvalue',
            name='mileage',
            field=models.FloatField(verbose_name='Пробег, км'),
        ),
        migrations.AlterField(
            model_name='defaultuservalues',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprise.enterprise'),
        ),
        migrations.AlterField(
            model_name='defaultuservalues',
            name='period_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='defaultuservalues',
            name='period_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='defaultuservalues',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='defaultuservalues',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle'),
        ),
    ]
