# Generated by Django 6.0 on 2026-04-10 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_enterprise_time_zone'),
        ('reports', '0005_carmileagereportvalue_count_trip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmileagereport',
            options={'verbose_name': 'Пробег автомобиля'},
        ),
        migrations.CreateModel(
            name='CarRoutesReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.report')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.enterprise')),
            ],
            options={
                'verbose_name': 'Маршруты автомобилей',
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='CarRoutesReportValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('path', models.JSONField(verbose_name='Маршруты')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
