# Generated by Django 6.0 on 2026-02-03 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True, verbose_name='Наименование')),
                ('city', models.CharField(max_length=25, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enterprise.enterprise', verbose_name='Предприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
                'unique_together': {('user', 'enterprise')},
            },
        ),
        migrations.AddField(
            model_name='enterprise',
            name='manager_users',
            field=models.ManyToManyField(related_name='managed_enterprises', through='enterprise.Manager', through_fields=('enterprise', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
