# Generated by Django 6.0 on 2026-07-14 10:56

import uuid

from django.db import migrations, models


def populate_manager_uuid(apps, schema_editor):
    Manager = apps.get_model("enterprise", "Manager")

    managers = Manager.objects.filter(uuid__isnull=True)

    for manager in managers.iterator(chunk_size=1000):
        manager.uuid = uuid.uuid4()
        manager.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("enterprise", "0002_enterprise_time_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="uuid",
            field=models.UUIDField(
                null=True,
                editable=False,
                verbose_name="UUID",
            ),
        ),
        migrations.RunPython(
            populate_manager_uuid,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="manager",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                editable=False,
                verbose_name="UUID",
            ),
        ),
    ]
