# Generated by Django 6.0 on 2026-07-14 11:13

import uuid
from django.db import migrations, models

def populate_enterprise_uuid(apps, schema_editor):
    Enterprise = apps.get_model("enterprise", "Enterprise")

    enterprises = Enterprise.objects.filter(uuid__isnull=True)

    for enterprise in enterprises.iterator(chunk_size=1000):
        enterprise.uuid = uuid.uuid4()
        enterprise.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("enterprise", "0003_manager_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="uuid",
            field=models.UUIDField(
                null=True,
                editable=False,
                verbose_name="UUID",
            ),
        ),
        migrations.RunPython(
            populate_enterprise_uuid,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                editable=False,
                verbose_name="UUID",
            ),
        ),
    ]
