# Generated by Django 6.0 on 2026-07-14 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0004_enterprise_uuid"),
    ]

    operations = [
        # Временно убираем UNIQUE(user_id, enterprise_id).
        migrations.AlterUniqueTogether(
            name="manager",
            unique_together=set(),
        ),

        # Добавляем новую nullable-связь по Enterprise.uuid.
        migrations.AddField(
            model_name="manager",
            name="enterprise_new",
            field=models.ForeignKey(
                to="enterprise.enterprise",
                to_field="uuid",
                db_column="enterprise_uuid",
                null=True,
                related_name="+",
                on_delete=django.db.models.deletion.RESTRICT,
                verbose_name="Предприятие",
            ),
        ),

        # Переносим существующие ссылки:
        # enterprise_id -> Enterprise.id -> Enterprise.uuid.
        migrations.RunSQL(
            sql="""
                UPDATE enterprise_manager AS manager
                SET enterprise_uuid = enterprise.uuid
                FROM enterprise_enterprise AS enterprise
                WHERE manager.enterprise_id = enterprise.id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Удаляем старую связь по bigint.
        migrations.RemoveField(
            model_name="manager",
            name="enterprise",
        ),

        # Новая связь снова называется enterprise.
        migrations.RenameField(
            model_name="manager",
            old_name="enterprise_new",
            new_name="enterprise",
        ),

        # Запрещаем NULL и приводим поле к итоговому состоянию модели.
        migrations.AlterField(
            model_name="manager",
            name="enterprise",
            field=models.ForeignKey(
                to="enterprise.enterprise",
                to_field="uuid",
                db_column="enterprise_uuid",
                on_delete=django.db.models.deletion.RESTRICT,
                verbose_name="Предприятие",
            ),
        ),

        # Восстанавливаем UNIQUE(user_id, enterprise_uuid).
        migrations.AlterUniqueTogether(
            name="manager",
            unique_together={("user", "enterprise")},
        ),
    ]