name: main-dev
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgis/postgis:16-3.5
        env:
          POSTGRES_DB: taxi_manager
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    env:
      DJANGO_SUPERUSER_NAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com 
      DJANGO_SUPERUSER_PASSWORD: admin
      SECRET_KEY: change-me
      PYTHONUNBUFFERED: 1
      DATABASE_URL: postgis://postgres:postgres@localhost:5432/taxi_manager  

    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true

      - name: Install GeoDjango System Dependencies
        run: make install-geo-deps-ci

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run manage.py test

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: metacortex687
          password: ${{ secrets.DOCKERHUB_TOKEN }}