name: main-dev
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgis/postgis:16-3.5
        env:
          POSTGRES_DB: taxi_manager
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    env:
      DJANGO_SUPERUSER_NAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com 
      DJANGO_SUPERUSER_PASSWORD: admin
      SECRET_KEY: change-me
      PYTHONUNBUFFERED: 1
      DATABASE_URL: postgis://postgres:postgres@localhost:5432/taxi_manager  
      LOCATIONIQ_KEY: ${{ secrets.LOCATIONIQ_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true

      - name: Install GeoDjango System Dependencies
        run: make install-geo-deps-ci

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run manage.py test

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: metacortex687
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: metacortex687/taxi-manager-dev:latest

      - name: Deploy using an SSH key
        uses: appleboy/ssh-action@v1
        with:
              host: ${{ secrets.DEV_HOST_IP }}
              username: ${{ secrets.DEV_HOST_USER }}
              key: ${{ secrets.DEV_HOST_SSH_PRIVATE_KEY }}
              port: ${{ secrets.DEV_HOST_PORT }}
              # passphrase: ${{ secrets.DEV_SSH_PASSPHRASE }}
              script: |
                set -euo pipefail
                APP_DIR="$HOME/taxi-manager"

                whoami
                ls -al

               
                mkdir -p "$APP_DIR"
                mkdir -p "$APP_DIR/data/logs/nginx"
                mkdir -p "$APP_DIR/data/goaccess"

                cd "$APP_DIR"

                curl -fsSL -o docker-compose.dev.yaml https://raw.githubusercontent.com/metacortex687/taxi-manager/main/docker-compose.dev.yaml
                curl -fsSL -o nginx.conf https://raw.githubusercontent.com/metacortex687/taxi-manager/main/nginx.conf


                export POSTGRES_USER="${{ secrets.DEV_POSTGRES_USER }}"
                export POSTGRES_PASSWORD="${{ secrets.DEV_POSTGRES_PASSWORD }}"
                export POSTGRES_DB="${{ secrets.DEV_POSTGRES_DB }}"
                export DJANGO_SUPERUSER_NAME="${{ secrets.DEV_DJANGO_SUPERUSER_NAME }}"
                export DJANGO_SUPERUSER_EMAIL="${{ secrets.DEV_DJANGO_SUPERUSER_EMAIL }}"
                export DJANGO_SUPERUSER_PASSWORD="${{ secrets.DEV_DJANGO_SUPERUSER_PASSWORD }}"
                export DJANGO_SECRET_KEY="${{ secrets.DEV_DJANGO_SECRET_KEY }}"
                export LOCATIONIQ_KEY="${{ secrets.LOCATIONIQ_KEY }}"
                export VK_BOT_TOKEN="${{ secrets.VK_BOT_TOKEN }}"
                export VK_BOT_GROUP_ID="${{ secrets.VK_BOT_GROUP_ID }}"
                
                docker compose -f docker-compose.dev.yaml pull
                docker compose -f docker-compose.dev.yaml up -d --no-build --force-recreate --remove-orphans

                docker compose -f docker-compose.dev.yaml ps





      