name: main
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true

      - name: Install GeoDjango System Dependencies
        run: make install-geo-deps-ci

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run manage.py test